### ISSUE TITLE
Statistical summaries module

### ISSUE THREAD

**Issue by rcpsilva** [marcosfpr/SEALy#1]
Thinking about measuring the correspondence of participants' models and tasks in a federation, it would be nice to be able to compute, averages, standard deviations, especially correlations in a privacy preserving manner.

**Comment by marcosfpr** [comment]
Sure thing! Right now, I'm enabling the homomorphic operations for floating point values (#2) using the CKKS scheme.

The currently supported BFV scheme don't support arithmetic with float values natively. We could try to use a trick and multiply the float values by a large value, generating an rounded integer to do the arithmetic. It works well in some cases, but I will try to support both schemes initially

**Comment by marcosfpr** [comment]
I will address this arithmetic primitives in the crate `dmt-crypto`. As soon as I have a PR I'll send here.

**Comment by marcosfpr** [comment]
closing as this became a simple FFI crate
